server:
  port: 8083

spring:
  application:
    name: vehicle-service


  datasource:
    url: jdbc:mysql://localhost:3306/spms
    username: root
    password: Ijse@123



  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
