spring:
  application:
    name: eureka-server
    version: test

  #nested
  #more readable
  #can use list(-)
  #boolean,number,string

  #use technologies
  #spring boot,kubernetes,docker,ci/cd pipeline

server:
  port: 8761

eureka:
  client:
    #server should not register itself as a service
    register-with-eureka: false
    #prevent fetching its own service list (client list)
    fetch-registry: false